global:
  scrape_interval: 5s

scrape_configs:
  - job_name: mysql
    metrics_path: /metrics
    static_configs:
      - targets:
          - mysql:3306
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: mysql_exporter:9104

  - job_name: 'blackbox-exporter'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
          - http://wordpress:80
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115