services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.4.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  mysql_exporter:
    container_name: mysql_exporter
    image: prom/mysqld-exporter:v0.17.2
    volumes:
      - ./mysql_exporter.cnf:/.my.cnf
    depends_on:
      mysql:
        condition: service_healthy

  wordpress:
    container_name: wordpress
    image: wordpress:php8.4-apache
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}:${DB_PORT}"
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .wp_data:/var/www/html

  blackbox_exporter:
    container_name: blackbox_exporter
    image: prom/blackbox-exporter:v0.27.0

  victoria_metrics:
    container_name: victoria_metrics
    image: victoriametrics/victoria-metrics:v1.121.0
    ports:
      - "8428:8428"
    volumes:
      - .victoria-metrics-data:/victoria-metrics-data
    command:
      - "-retentionPeriod=2w"
      - "-storageDataPath=/victoria-metrics-data"
